services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: requestmart_app
    ports:
      - "8080:80"
    volumes:
      - ./../:/var/www/html/Request-Based-Marketplace/
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/Request-Based-Marketplace/public
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: requestmart_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vishak@123
      MYSQL_DATABASE: products_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./../database/products_db.sql:/docker-entrypoint-initdb.d/products_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:
